/******************************************************************************
	File: 	AMT_8_5_FILTER_CONFIG_Data_Load_1_Report.sql

	Description:	Creates report configuration in the database

**************************************************************************************************************
	Change History
**************************************************************************************************************
Date:		Author:		Description:
--------	--------	----------------------------------------
16 Aug 11	VV			Mod: BUDGET_PlantHire_P_L
18 Aug 11   TP          Mod: Rpt_455_Generic_Interface_Log
23 Aug 11	TP			Mod: Rpt_160_Daily_Machine_Performance_Check_Sheet
23 Aug 11	TP			Mod: Rpt_185_Labour_Hrs_Variance_Analysis
23 Aug 11	TP			Mod: Rpt_236_Summary_Analysis
30 Aug 11   TP			Mod: BUDGET_CostPerUOM_Total
30 Aug 11	TP			Mod: Rpt_361_BUDGET_Total_Cost_Per_UOM_Report
**END OF HISTORY************************************************************************************************************/

DECLARE @FilterConfigName VARCHAR(100),@FilterConfigXML xml,@FilterTypeID int

SET @FilterTypeID=1	--Report

--BUDGET_PlantHire_P_L
SET @FilterConfigName = 'BUDGET_PlantHire_P_L'
SET @FilterConfigXML='	<BUDGET_PlantHire_P_L>
		<ReportName>Plant Hire P and L</ReportName>
		<InitialParams>BudgetHeaderId,BudgetName,PeriodStart,PeriodEnd</InitialParams>
		<DefaultType>Text</DefaultType>
		<ReportTypes>
			<Text>
				<ReportFile>Plant_Hire_P_L_Text.rdlc</ReportFile>
				<ReportParams>
					<BudgetName>|InitialParams.BudgetName|</BudgetName>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
				</ReportParams>
				<StoredProcedure>BUDGET_RPT_PLANT_HIRE_P_L_P</StoredProcedure>
				<SpParams>
					<BudgetHeaderID>|InitialParams.BudgetHeaderId|</BudgetHeaderID>
					<EntireBudget>|dSelector.CheckBox.Checked|</EntireBudget>
					<StartPeriod>|dSelector.PeriodValue1|</StartPeriod>
					<EndPeriod>|dSelector.PeriodValue2|</EndPeriod>
					<Branch>|schBranch.SelectedItemsNoAp|</Branch>
					<Site>|schSite.SelectedItemsNoAp|</Site>
					<Fleet>|schFleet.SelectedItemsNoAp|</Fleet>
					<BudgetEquipmentId>|schEquipment.SelectedItemsNoAp|</BudgetEquipmentId>
					<ManufacturerId>|schManufacturer.SelectedItemsNoAp|</ManufacturerId>
					<ModelId>|schModel.SelectedItemsNoAp|</ModelId>
					<EquipmentGroupId>|schEqpGroup.SelectedItemsNoAp|</EquipmentGroupId>
					<EquipmentClassId>|schEqpClass.SelectedItemsNoAp|</EquipmentClassId>
					<RegionId>|schRegion.SelectedItemsNoAp|</RegionId>
					<DivisionId>|schDivision.SelectedItemsNoAp|</DivisionId>
					<EquipmentLocationId>|schEqpLocation.SelectedItemsNoAp|</EquipmentLocationId>
					<EquipmentCriticalityId>|schEqpCriticality.SelectedItemsNoAp|</EquipmentCriticalityId>
					<EquipmentCategoryId>|schEqpCategory.SelectedItemsNoAp|</EquipmentCategoryId>
					<IndustryGroupId>|schIndGroup.SelectedItemsNoAp|</IndustryGroupId>
					<CostResponsibilityId>|schCostResp.SelectedItemsNoAp|</CostResponsibilityId>
					<CostCentreID>|schCostCentre.SelectedItemsNoAp|</CostCentreID>
					<CC_Activity>|schCCActivity.SelectedItemsNoAp|</CC_Activity>
					<CC_Location>|schCCLocation.SelectedItemsNoAp|</CC_Location>
					<CC_Responsibility>|schCCResponsibility.SelectedItemsNoAp|</CC_Responsibility>
					<CostExpenseID>|schCostExpense.SelectedItemsNoAp|</CostExpenseID>
					<ParentEquipmentID>|ParentEquipment.SelectedItemsNoAp|</ParentEquipmentID>
					<ProjectId>|schProject.SelectedItemsNoAp|</ProjectId>
					<PHProjectId>|schPHProject.SelectedItemsNoAp|</PHProjectId>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<PeriodStart>|InitialParams.PeriodStart|</PeriodStart>
								<PeriodEnd>|InitialParams.PeriodEnd|</PeriodEnd>
							</Properties>
						</ControlParams>
					</DateSelector>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schBudHeader</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetHeader</DataType>
								<Text>|InitialParams.BudgetName|</Text>
								<SelectedItems>|InitialParams.BudgetHeaderId|</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schBranch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetBranch</DataType>
								<Caption>Branch</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schSite</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetSite</DataType>
								<Caption>Site</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schFleet</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetFleet</DataType>
								<Caption>Fleet</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schEqpClass</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetEqpClass</DataType>
								<Caption>Eqp Class</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schEqpGroup</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetEqpGroup</DataType>
								<Caption>Eqp Group</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schManufacturer</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetManufacturer</DataType>
								<Caption>Manufacturer</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schModel</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetModel</DataType>
								<Caption>Model</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schEquipment</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetEquipment</DataType>
								<Caption>Equipment</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schRegion</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetRegion</DataType>
								<Caption>Region</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schDivision</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetDivision</DataType>
								<Caption>Division</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schEqpCriticality</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetEqpCriticality</DataType>
								<Caption>Eqp Criticality</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schEqpLocation</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetEqpLocation</DataType>
								<Caption>Eqp Location</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schEqpCategory</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetEqpCategory</DataType>
								<Caption>Eqp Category</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schCostResp</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetCostResponsibility</DataType>
								<Caption>Cost Responsibility</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schIndGroup</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetIndustryGroup</DataType>
								<Caption>Industry Group</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>ParentEquipment</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetParentEquipment</DataType>
								<Caption>Parent Equipment</Caption>
								<MultiSelector>false</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schProject</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetProjectStartDate</DataType>
								<Caption>Project - Equipment</Caption>
								<MultiSelector>false</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schPHProject</ControlName>
						<ControlParams>
							<Properties>
								<DataType>EqpSel_BudgetProject</DataType>
								<Caption>Project</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostExpense</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostExpense</DataType>
								<Caption>Expense Element</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostCentre</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostCentre</DataType>
								<Caption>Cost Centre</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCActivity</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CCActivity</DataType>
								<Caption>CC Activity</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCLocation</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CCLocation</DataType>
								<Caption>CC Location</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCResponsibility</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CCResponsibility</DataType>
								<Caption>CC Responsibility</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
				</ReportControls>
			</Text>
		</ReportTypes>
	</BUDGET_PlantHire_P_L>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END

SET @FilterConfigName = 'Rpt_455_Generic_Interface_Log'
SET @FilterConfigXML='	<Rpt_455_Generic_Interface_Log>
		<ReportName>Generic Interface Log</ReportName>
		<InitialParams></InitialParams>
		<ReportTypes>
			<Text>
				<ReportFile>GenericInterfaceLog_Text.rdlc</ReportFile>
				<ReportParams>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
				</ReportParams>
				<StoredProcedure>RPT_GENERIC_INTERFACE_LOG_P</StoredProcedure>
				<SpParams>
					<StartDate>|dSelector.DateTimeValue1MonthBegin|</StartDate>
					<EndDate>|dSelector.DateTimeValue2MonthEnd|</EndDate>
					<ImportFileName>|ImpFile.TextBox.Text|</ImportFileName>
				    <ImportErrorTypeId>|ImportErrorType.SelectedItems|</ImportErrorTypeId>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<PeriodStart></PeriodStart>
								<PeriodEnd></PeriodEnd>
								<ShowFutureDate>false</ShowFutureDate>
								<Type>Yesterday</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>ImportErrorType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ImportErrorType</DataType>
								<MultiSelector>true</MultiSelector>
								<Text>(-1/4) ***</Text>
								<SelectedItems>1,2,3</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>					
					<LabeledTextBox>
						<Group>Filters</Group>
						<ControlName>ImpFile</ControlName>
						<ControlParams>
							<Properties>
								<Label.Text>Import Reference</Label.Text>
								<TextBox.Font.Style>Regular</TextBox.Font.Style>
								<TextBox.TextAlign>Left</TextBox.TextAlign>
							</Properties>
						</ControlParams>
					</LabeledTextBox>
				</ReportControls>
			</Text>
		</ReportTypes>
	</Rpt_455_Generic_Interface_Log>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END

--Rpt_160_Daily_Machine_Performance_Check_Sheet
SET @FilterConfigName = 'Rpt_160_Daily_Machine_Performance_Check_Sheet'
SET @FilterConfigXML='	<Rpt_160_Daily_Machine_Performance_Check_Sheet>
		<ReportName>Daily Machine Performance Check Sheet</ReportName>
		<InitialParams>ControlType,IDlist,TextList,Responsibility,ProjectionTypes</InitialParams>
		<ReportTypes>
			<Text>
				<ReportFile>DailyMachinePerformanceCheckSheet.rpt</ReportFile>
				<ReportParams>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
				</ReportParams>
				<StoredProcedure>REP_DAILY_PERF_CHECK_SHEET_P</StoredProcedure>
				<SpParams>
					<StartDate>|dSelector.DateTimeValue1MonthBegin|</StartDate>
					<EndDate>|dSelector.DateTimeValue2MonthNext|</EndDate>
					<DealerId>1</DealerId>
					<ResponsibilityID>|DTResponsibility.SelectedItems|</ResponsibilityID>
					<EqpPlanID>|Equipment.SelectedItems|</EqpPlanID>
					<TaskTypeID>|TaskType.SelectedItems|</TaskTypeID>
					<SystemId>|System.SelectedItems|</SystemId>
					<BranchID>|Branch.SelectedItems|</BranchID>
					<SiteID>|Site.SelectedItems|</SiteID>
					<FleetID>|Fleet.SelectedItems|</FleetID>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<Type>NCB_Today</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Branch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Branch</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Site</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Site</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Fleet</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>Fleet</DataType>
								<Caption>Fleet *</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Equipment</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>Equipment</DataType>
								<Caption>Equipment *</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>DTResponsibility</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Responsibility</DataType>
								<MultiSelector>true</MultiSelector>
								<Caption>DTResponsibility +</Caption>
								<Text>|InitialParams.Responsibility|</Text>
								<SelectedItems>|InitialParams.ResponsibilityID|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>System</ControlName>
						<ControlParams>
							<Properties>
								<DataType>System</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<Label>
						<Group>Filters</Group>
						<ControlName>lbl</ControlName>
						<ControlParams>
							<Properties>
								<Width>270</Width>
								<TextAlign>MiddleLeft</TextAlign>
								<Text>+ Downtime Responsibility filter</Text>
								<Font.Style>Regular</Font.Style>
								<Tag>Dont Display</Tag>
							</Properties>
						</ControlParams>
					</Label>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>TaskType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>TaskType</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_System_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_System_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_System_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_System_StrategyTask</DataType>
								<SelectedItems>0</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_TaskType_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_TaskType_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Branch_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Branch_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Site_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Site_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Fleet_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Fleet_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Equipment_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Equipment_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>ProjectionTypeRestricted</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ProjectionTypeRestricted</DataType>
								<SelectedItems>|InitialParams.ProjectionTypes|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
				</ReportControls>
			</Text>
		</ReportTypes>
	</Rpt_160_Daily_Machine_Performance_Check_Sheet>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END

--Rpt_185_Labour_Hrs_Variance_Analysis
SET @FilterConfigName = 'Rpt_185_Labour_Hrs_Variance_Analysis'
SET @FilterConfigXML='	<Rpt_185_Labour_Hrs_Variance_Analysis>
		<ReportName>Labour Hrs Variance Analysis</ReportName>
		<InitialParams>ControlType,IDlist,TextList,ProjectionTypes</InitialParams>
		<DefaultType>Text</DefaultType>
		<ReportTypes>
			<Text>
				<ReportFile>LabourVarianceAnalysis_Details.rpt</ReportFile>
				<ReportParams>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
					<txtHeader>|ddlAnalyseBy.SelectedText|</txtHeader>
					<ReportHeader>Labour Hours Variance Analysis</ReportHeader>
					<AnalyseBy>|ddlAnalyseBy.SelectedText|</AnalyseBy>
				</ReportParams>
				<StoredProcedure>RPT_LABOUR_VARIANCE_ANALYSIS_P</StoredProcedure>
				<SpParams>
					<PlanToCurrentMonth>|dSelector.CheckBox.Checked|</PlanToCurrentMonth>
					<StartDate>|dSelector.DateTimeValue1MonthBegin|</StartDate>
					<EndDate>|dSelector.DateTimeValue2MonthNext|</EndDate>
					<ShowTasks>|rbcShow.Value|</ShowTasks>
					<DealerId>1</DealerId>
					<Planned>|rbcPlanned.Value|</Planned>
					<BreakDown>|rbcBreakdown.Value|</BreakDown>
					<WorkGroupID>|WorkGroup.SelectedItems|</WorkGroupID>
					<EmployeeID>|Employee.SelectedItems|</EmployeeID>
					<AnalyseBy>|ddlAnalyseBy.SelectedItem|</AnalyseBy>
					<TaskHeaderId>|ProjTask.SelectedItems|</TaskHeaderId>
					<ModifierCodeID>|ModCode.SelectedItems|</ModifierCodeID>
					<TaskTypeID>|TaskType.SelectedItems|</TaskTypeID>
					<SystemID>|System.SelectedItems|</SystemID>
					<SubSystemID>|SubSystem.SelectedItems|</SubSystemID>
					<ComponentCodeID>|CompCode.SelectedItems|</ComponentCodeID>
					<EqpPlanID>|Equipment.SelectedItems|</EqpPlanID>
					<ModelId>|Model.SelectedItems|</ModelId>
					<CostTypeID>|CostType.SelectedItems|</CostTypeID>
					<BranchId>|Branch.SelectedItems|</BranchId>
					<SiteID>|Site.SelectedItems|</SiteID>
					<FleetID>|Fleet.SelectedItems|</FleetID>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<Type>PlanToCurrentMonth</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<DropdownListControl>
						<Group>AnalyseBy</Group>
						<ControlName>ddlAnalyseBy</ControlName>
						<ControlParams>
							<Items>
								<Item>BRAN,Branch</Item>
								<Item>SITE,Site</Item>
								<Item>FLEE,Fleet</Item>
								<Item>MODL,Model</Item>
								<Item>EQPL,Equipment Plan</Item>
								<Item>PLAN,Planned</Item>
								<Item>BREA,Breakdown</Item>
								<Item>PRTA,Strategy Task</Item>
								<Item>EVTT,Task Type</Item>
								<Item>EVCC,Component Code</Item>
								<Item>CTTY,Cost Type</Item>
								<Item>SYST,System</Item>
								<Item>SUBS,Sub System</Item>
								<Item>WRGP,Work Group</Item>
								<Item>EMPL,Employee</Item>
								<Item>WORK,Work Order</Item>
								<Item>TASK,Task</Item>
								<Item>MONH,Month</Item>
								<Item>QRTR,Quarter</Item>
								<Item>YEAR,Year</Item>
							</Items>
							<Properties>
								<Group.Text>Analyse By</Group.Text>
							</Properties>
						</ControlParams>
					</DropdownListControl>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Branch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Branch</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Site</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Site</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Model</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Model</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Fleet</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Fleet</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Equipment</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Equipment</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>CostType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostType</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>System</ControlName>
						<ControlParams>
							<Properties>
								<DataType>System</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>SubSystem</ControlName>
						<ControlParams>
							<Properties>
								<DataType>SubSystem</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>WorkGroup</ControlName>
						<ControlParams>
							<Properties>
								<DataType>WorkGroup</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcPlanned</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>3</NumberOfRadioButtons>
								<RadioButton1.Text>All</RadioButton1.Text>
								<RadioButton2.Text>Yes</RadioButton2.Text>
								<RadioButton3.Text>No</RadioButton3.Text>
								<Width>272</Width>
								<Group.Width>78</Group.Width>
								<RadioButton1.Width>70</RadioButton1.Width>
								<RadioButton2.Width>70</RadioButton2.Width>
								<RadioButton3.Width>70</RadioButton3.Width>
								<RadioButtonValue1>1</RadioButtonValue1>
								<RadioButtonValue2>2</RadioButtonValue2>
								<RadioButtonValue3>3</RadioButtonValue3>
								<Group.Text>Planned</Group.Text>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcBreakdown</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>3</NumberOfRadioButtons>
								<RadioButton1.Text>All</RadioButton1.Text>
								<RadioButton2.Text>Yes</RadioButton2.Text>
								<RadioButton3.Text>No</RadioButton3.Text>
								<Width>272</Width>
								<Group.Width>78</Group.Width>
								<RadioButton1.Width>70</RadioButton1.Width>
								<RadioButton2.Width>70</RadioButton2.Width>
								<RadioButton3.Width>70</RadioButton3.Width>
								<RadioButtonValue1>1</RadioButtonValue1>
								<RadioButtonValue2>2</RadioButtonValue2>
								<RadioButtonValue3>3</RadioButtonValue3>
								<Group.Text>Breakdown</Group.Text>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcShow</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>3</NumberOfRadioButtons>
								<RadioButton1.Text>All Workorders</RadioButton1.Text>
								<RadioButton2.Text>Only Workorders with Expected Labour Hours set</RadioButton2.Text>
								<RadioButton3.Text>Only Workorders with Expected Labour Hours set and linked to Workorder Settlements</RadioButton3.Text>
								<Width>500</Width>
								<Group.Width>78</Group.Width>
								<RadioButton1.Width>70</RadioButton1.Width>
								<RadioButton2.Width>70</RadioButton2.Width>
								<RadioButton3.Width>70</RadioButton3.Width>
								<RadioButtonValue1>0</RadioButtonValue1>
								<RadioButtonValue2>1</RadioButtonValue2>
								<RadioButtonValue3>2</RadioButtonValue3>
								<Group.Text>Show</Group.Text>
								<Group.Font.Style>Bold</Group.Font.Style>
								<FlowLayout>true</FlowLayout>
								<RadioButton3.Checked>true</RadioButton3.Checked>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>ProjTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>TaskHeader</DataType>
								<MultiSelector>true</MultiSelector>
								<Caption>Strategy Task</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>CompCode</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CompCode</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>TaskType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>TaskType</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>ModCode</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ModCode</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Employee</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Employee</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_CostType_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_CostType_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_CostType_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_CostType_StrategyTask</DataType>
								<SelectedItems>0</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_SubSystem_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_SubSystem_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_SubSystem_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_SubSystem_StrategyTask</DataType>
								<SelectedItems>0</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_WorkGroup_EQS</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_WorkGroup_EQS</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_CompCode_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_CompCode_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_TaskType_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_TaskType_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_ModCode_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_ModCode_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_Model_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Model_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Branch_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Branch_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Site_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Site_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Fleet_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Fleet_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Equipment_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Equipment_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>ProjectionTypeRestricted</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ProjectionTypeRestricted</DataType>
								<SelectedItems>|InitialParams.ProjectionTypes|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
				</ReportControls>
			</Text>
			<Bar>
				<ReportFile>LabourVarianceAnalysis_Bar.rpt</ReportFile>
				<ReportParams>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
					<ReportHeader>Labour Hours Variance Analysis</ReportHeader>
					<AnalyseBy>|ddlAnalyseBy.SelectedText|</AnalyseBy>
				</ReportParams>
				<StoredProcedure>RPT_LABOUR_VARIANCE_ANALYSIS_P</StoredProcedure>
				<SpParams>
					<PlanToCurrentMonth>|dSelector.CheckBox.Checked|</PlanToCurrentMonth>
					<StartDate>|dSelector.DateTimeValue1MonthBegin|</StartDate>
					<EndDate>|dSelector.DateTimeValue2MonthNext|</EndDate>
					<ShowTasks>|rbcShow.Value|</ShowTasks>
					<DealerId>1</DealerId>
					<Planned>|rbcPlanned.Value|</Planned>
					<BreakDown>|rbcBreakdown.Value|</BreakDown>
					<WorkGroupID>|WorkGroup.SelectedItems|</WorkGroupID>
					<EmployeeID>|Employee.SelectedItems|</EmployeeID>
					<AnalyseBy>|ddlAnalyseBy.SelectedItem|</AnalyseBy>
					<TaskHeaderId>|ProjTask.SelectedItems|</TaskHeaderId>
					<ModifierCodeID>|ModCode.SelectedItems|</ModifierCodeID>
					<TaskTypeID>|TaskType.SelectedItems|</TaskTypeID>
					<SystemID>|System.SelectedItems|</SystemID>
					<SubSystemID>|SubSystem.SelectedItems|</SubSystemID>
					<ComponentCodeID>|CompCode.SelectedItems|</ComponentCodeID>
					<EqpPlanID>|Equipment.SelectedItems|</EqpPlanID>
					<ModelId>|Model.SelectedItems|</ModelId>
					<CostTypeID>|CostType.SelectedItems|</CostTypeID>
					<BranchId>|Branch.SelectedItems|</BranchId>
					<SiteID>|Site.SelectedItems|</SiteID>
					<FleetID>|Fleet.SelectedItems|</FleetID>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<Type>PlanToCurrentMonth</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<DropdownListControl>
						<Group>AnalyseBy</Group>
						<ControlName>ddlAnalyseBy</ControlName>
						<ControlParams>
							<Items>
								<Item>BRAN,Branch</Item>
								<Item>SITE,Site</Item>
								<Item>FLEE,Fleet</Item>
								<Item>MODL,Model</Item>
								<Item>EQPL,Equipment Plan</Item>
								<Item>PLAN,Planned</Item>
								<Item>BREA,Breakdown</Item>
								<Item>PRTA,Strategy Task</Item>
								<Item>EVTT,Task Type</Item>
								<Item>EVCC,Component Code</Item>
								<Item>CTTY,Cost Type</Item>
								<Item>SYST,System</Item>
								<Item>SUBS,Sub System</Item>
								<Item>WRGP,Work Group</Item>
								<Item>EMPL,Employee</Item>
								<Item>WORK,Work Order</Item>
								<Item>TASK,Task</Item>
								<Item>MONH,Month</Item>
								<Item>QRTR,Quarter</Item>
								<Item>YEAR,Year</Item>
							</Items>
							<Properties>
								<Group.Text>Analyse By</Group.Text>
							</Properties>
						</ControlParams>
					</DropdownListControl>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Branch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Branch</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Site</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Site</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Model</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Model</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Fleet</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Fleet</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Equipment</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Equipment</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>CostType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostType</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>System</ControlName>
						<ControlParams>
							<Properties>
								<DataType>System</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>SubSystem</ControlName>
						<ControlParams>
							<Properties>
								<DataType>SubSystem</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>WorkGroup</ControlName>
						<ControlParams>
							<Properties>
								<DataType>WorkGroup</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcPlanned</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>3</NumberOfRadioButtons>
								<RadioButton1.Text>All</RadioButton1.Text>
								<RadioButton2.Text>Yes</RadioButton2.Text>
								<RadioButton3.Text>No</RadioButton3.Text>
								<Width>272</Width>
								<Group.Width>78</Group.Width>
								<RadioButton1.Width>70</RadioButton1.Width>
								<RadioButton2.Width>70</RadioButton2.Width>
								<RadioButton3.Width>70</RadioButton3.Width>
								<RadioButtonValue1>1</RadioButtonValue1>
								<RadioButtonValue2>2</RadioButtonValue2>
								<RadioButtonValue3>3</RadioButtonValue3>
								<Group.Text>Planned</Group.Text>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcBreakdown</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>3</NumberOfRadioButtons>
								<RadioButton1.Text>All</RadioButton1.Text>
								<RadioButton2.Text>Yes</RadioButton2.Text>
								<RadioButton3.Text>No</RadioButton3.Text>
								<Width>272</Width>
								<Group.Width>78</Group.Width>
								<RadioButton1.Width>70</RadioButton1.Width>
								<RadioButton2.Width>70</RadioButton2.Width>
								<RadioButton3.Width>70</RadioButton3.Width>
								<RadioButtonValue1>1</RadioButtonValue1>
								<RadioButtonValue2>2</RadioButtonValue2>
								<RadioButtonValue3>3</RadioButtonValue3>
								<Group.Text>Breakdown</Group.Text>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcShow</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>3</NumberOfRadioButtons>
								<RadioButton1.Text>All Workorders</RadioButton1.Text>
								<RadioButton2.Text>Only Workorders with Expected Labour Hours set</RadioButton2.Text>
								<RadioButton3.Text>Only Workorders with Expected Labour Hours set and linked to Workorder Settlements</RadioButton3.Text>
								<Width>500</Width>
								<Group.Width>78</Group.Width>
								<RadioButton1.Width>70</RadioButton1.Width>
								<RadioButton2.Width>70</RadioButton2.Width>
								<RadioButton3.Width>70</RadioButton3.Width>
								<RadioButtonValue1>0</RadioButtonValue1>
								<RadioButtonValue2>1</RadioButtonValue2>
								<RadioButtonValue3>2</RadioButtonValue3>
								<Group.Text>Show</Group.Text>
								<Group.Font.Style>Bold</Group.Font.Style>
								<FlowLayout>true</FlowLayout>
								<RadioButton3.Checked>true</RadioButton3.Checked>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>ProjTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>TaskHeader</DataType>
								<MultiSelector>true</MultiSelector>
								<Caption>Strategy Task</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>CompCode</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CompCode</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>TaskType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>TaskType</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>ModCode</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ModCode</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Employee</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Employee</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_CostType_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_CostType_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_CostType_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_CostType_StrategyTask</DataType>
								<SelectedItems>0</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_SubSystem_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_SubSystem_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_SubSystem_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_SubSystem_StrategyTask</DataType>
								<SelectedItems>0</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_WorkGroup_EQS</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_WorkGroup_EQS</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_CompCode_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_CompCode_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_TaskType_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_TaskType_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_ModCode_EQSTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_ModCode_EQSTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_Model_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Model_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Branch_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Branch_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Site_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Site_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Fleet_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Fleet_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Equipment_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Equipment_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>ProjectionTypeRestricted</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ProjectionTypeRestricted</DataType>
								<SelectedItems>|InitialParams.ProjectionTypes|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
				</ReportControls>
			</Bar>
		</ReportTypes>
	</Rpt_185_Labour_Hrs_Variance_Analysis>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END

--Rpt_236_Summary_Analysis
SET @FilterConfigName = 'Rpt_236_Summary_Analysis'
SET @FilterConfigXML='	<Rpt_236_Summary_Analysis>
		<ReportName>Summary Analysis</ReportName>
		<InitialParams>ControlType,IDlist,TextList,CostBearer,QUOM,ProjectionTypes</InitialParams>
		<ReportTypes>
			<Text>
				<ReportFile>EqpEvalSummary.rpt</ReportFile>
				<ReportParams>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
					<AnalyseBy>|ddlAnalyseBy.SelectedText|</AnalyseBy>
					<txtUOMDescr>|SpParams.UOM|</txtUOMDescr>
					<txtRevenuePerUOM>INT32|SpParams.RevenuePerUOM|</txtRevenuePerUOM>
					<txtAnnualDiscountFactor>INT32|SpParams.AnnDiscFactor|</txtAnnualDiscountFactor>
				</ReportParams>
				<DirtyCheck>
					<BranchId>|Branch.SelectedItemsNoAp|</BranchId>
					<SiteId>|Site.SelectedItemsNoAp|</SiteId>
					<ModelId>|Model.SelectedItemsNoAp|</ModelId>
					<FleetId>|Fleet.SelectedItemsNoAp|</FleetId>
					<EqpPlanId>|Equipment.SelectedItemsNoAp|</EqpPlanId>
					<EqpProjHeaderId>|Projection.SelectedItemsNoAp|</EqpProjHeaderId>
					<CheckDirtyEqpUsage>1</CheckDirtyEqpUsage>
					<CheckDirtyNextOcc>1</CheckDirtyNextOcc>
					<CheckDirtyProjOcc>1</CheckDirtyProjOcc>
					<CheckDirtyActCost>1</CheckDirtyActCost>
					<CheckDirtyProjCost>1</CheckDirtyProjCost>
					<CheckDirtyBillings>1</CheckDirtyBillings>
					<CheckDirtyBudget>0</CheckDirtyBudget>
				</DirtyCheck>
				<StoredProcedure>RPT_EQUIPMENT_EVALUATION_P</StoredProcedure>
				<SpParams>
					<RevenuePerUOM>OUTPUT |Revenue.TextBox.Text|</RevenuePerUOM>
					<AnnDiscFactor>OUTPUT |DiscountFactor.TextBox.Text|</AnnDiscFactor>
					<Parts_Labour_Misc>|rbcCosts.Value|</Parts_Labour_Misc>
					<ContractID>|Contract.SelectedItems|</ContractID>
					<Start_Date>|dSelector.PeriodValue1NullIfChecked|</Start_Date>
					<End_Date>|dSelector.PeriodValue2NullIfChecked|</End_Date>
					<DealerId>1</DealerId>
					<ProjHeaderId>|Projection.SelectedItemsNoAp|</ProjHeaderId>
					<QUOMID>|QUOM.SelectedItemsNoAp|</QUOMID>
					<CostTypeID>|CostType.SelectedItemsNoAp|</CostTypeID>
					<AnalyseBy>|ddlAnalyseBy.SelectedItem|</AnalyseBy>
					<UOM>OUTPUT </UOM>
					<EqpPlanID>|Equipment.SelectedItemsNoAp|</EqpPlanID>
					<CostBearerID>|CostBearer.SelectedItemsNoAp|</CostBearerID>
					<ModelId>|Model.SelectedItemsNoAp|</ModelId>
					<BranchId>|Branch.SelectedItemsNoAp|</BranchId>
					<SiteID>|Site.SelectedItemsNoAp|</SiteID>
					<FleetID>|Fleet.SelectedItemsNoAp|</FleetID>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<Type>EntirePlanTerm</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<DropdownListControl>
						<Group>AnalyseBy</Group>
						<ControlName>ddlAnalyseBy</ControlName>
						<ControlParams>
							<Items>
								<Item>MONH,Month</Item>
								<Item>YEAR,Year</Item>
							</Items>
							<Properties>
								<Group.Text>Analyse By</Group.Text>
							</Properties>
						</ControlParams>
					</DropdownListControl>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Branch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Branch</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Site</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Site</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Model</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Model</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Fleet</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Fleet</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Equipment</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Equipment</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Projection</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>Projection</DataType>
								<Caption>Projection Type *</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>QUOM</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>QUOM</DataType>
								<Caption>+UOM *</Caption>
								<Text>|InitialParams.QUOM|</Text>
								<SelectedItems>|InitialParams.QUOMID|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>CostType</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostType</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Contract</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Contract</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcCosts</ControlName>
						<ControlParams>
							<Properties>
								<NumberOfRadioButtons>4</NumberOfRadioButtons>
								<RadioButton1.Text>All</RadioButton1.Text>
								<RadioButton2.Text>Parts</RadioButton2.Text>
								<RadioButton3.Text>Labour</RadioButton3.Text>
								<RadioButton4.Text>Misc</RadioButton4.Text>
								<Width>272</Width>
								<Group.Width>70</Group.Width>
								<RadioButton1.Width>40</RadioButton1.Width>
								<RadioButton2.Width>55</RadioButton2.Width>
								<RadioButton3.Width>60</RadioButton3.Width>
								<RadioButton4.Width>54</RadioButton4.Width>
								<RadioButtonValue1>0</RadioButtonValue1>
								<RadioButtonValue2>1</RadioButtonValue2>
								<RadioButtonValue3>2</RadioButtonValue3>
								<RadioButtonValue4>3</RadioButtonValue4>
								<Group.Text>Costs</Group.Text>
								<DisplayCaptionAs>P/L/M</DisplayCaptionAs>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
					<Label>
						<Group>Filters</Group>
						<ControlName>lbl</ControlName>
						<ControlParams>
							<Properties>
								<Width>370</Width>
								<TextAlign>MiddleLeft</TextAlign>
								<Text>+ The UOM Selected is used as a basis for the equipment evaluation.</Text>
								<Font.Style>Regular</Font.Style>
								<Tag>Dont Display</Tag>
							</Properties>
						</ControlParams>
					</Label>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>CostBearer</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostBearer</DataType>
								<MultiSelector>true</MultiSelector>
								<Text>|InitialParams.CostBearer|</Text>
								<SelectedItems>|InitialParams.CostBearerID|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<LabeledTextBox>
						<Group>Filters</Group>
						<ControlName>DiscountFactor</ControlName>
						<ControlParams>
							<Properties>
								<Label.Text>Discount Factor %</Label.Text>
								<TextBox.Font.Style>Regular</TextBox.Font.Style>
								<TextBox.TextAlign>Right</TextBox.TextAlign>
							</Properties>
						</ControlParams>
					</LabeledTextBox>
					<LabeledTextBox>
						<Group>Filters</Group>
						<ControlName>Revenue</ControlName>
						<ControlParams>
							<Properties>
								<Label.Text>Revenue</Label.Text>
								<TextBox.Font.Style>Regular</TextBox.Font.Style>
								<TextBox.TextAlign>Right</TextBox.TextAlign>
							</Properties>
						</ControlParams>
					</LabeledTextBox>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_Model_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Model_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_QUOM_SelectCommonQUOM</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_QUOM_SelectCommonQUOM</DataType>
								<SelectedItems>0</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>Constants_QUOM_All</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_QUOM_All</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Branch_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Branch_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Site_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Site_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Fleet_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Fleet_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>Constants_Equipment_StrategyTask</ControlName>
						<ControlParams>
							<Properties>
								<DataType>Constants_Equipment_StrategyTask</DataType>
								<SelectedItems>1</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>ProjectionTypeRestricted</ControlName>
						<ControlParams>
							<Properties>
								<DataType>ProjectionTypeRestricted</DataType>
								<SelectedItems>|InitialParams.ProjectionTypes|</SelectedItems>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
				</ReportControls>
			</Text>
		</ReportTypes>
	</Rpt_236_Summary_Analysis>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END

--BUDGET_CostPerUOM_Total
SET @FilterConfigName = 'BUDGET_CostPerUOM_Total'
SET @FilterConfigXML='	<BUDGET_CostPerUOM_Total>
		<ReportName>Total Cost Per UOM</ReportName>
		<InitialParams>BudgetHeaderId,BudgetName,PeriodStart,PeriodEnd,Enable_Cost_At_Cost</InitialParams>
		<ReportTypes>
			<Text>
				<ReportFile>BudgetComparisonHighLevel.rpt</ReportFile>
				<ReportParams>
					<ReportHeader>Budget Comparison - High Level</ReportHeader>
					<BudgetName>|InitialParams.BudgetName|</BudgetName>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
					<UOM>|schUOM.Text|</UOM>
					<txtCol1>|schAnalyseBy.Text|</txtCol1>
				</ReportParams>
				<StoredProcedure>BUDGET_RPT_COMPARISON_HIGH_LEVEL_P</StoredProcedure>
				<SpParams>
					<BudgetHeader1ID>|InitialParams.BudgetHeaderId|</BudgetHeader1ID>
					<UOMID>|schUOM.SelectedItems|</UOMID>
					<Next12Months>|dSelector.CheckBox.Checked|</Next12Months>
					<StartDate>|dSelector.PeriodValue1|</StartDate>
					<EndDate>|dSelector.PeriodValue2|</EndDate>
					<AnalyseBy>|dllAnalyseBy.SelectedItems|</AnalyseBy>
					<IncludeOverheads>|cbcOHEQP.CheckBox1.Checked|</IncludeOverheads>
					<IncludeEquipment>|cbcOHEQP.CheckBox2.Checked|</IncludeEquipment>
					<IncludeActuals>|cbcCost.CheckBox1.Checked|</IncludeActuals>
					<IncludeProjected>|cbcCost.CheckBox2.Checked|</IncludeProjected>
					<Branch>|schBranch.SelectedItems|</Branch>
					<Site>|schSite.SelectedItems|</Site>
					<Fleet>|schFleet.SelectedItems|</Fleet>
					<CCActivity>|schCCActivity.SelectedItems|</CCActivity>
					<CCLocation>|schCCLocation.SelectedItems|</CCLocation>
					<CCResponsibility>|schCCResponsibility.SelectedItems|</CCResponsibility>
					<CostCentreID>|schCostCentre.SelectedItems|</CostCentreID>
					<CostExpenseID>|schCostExpense.SelectedItems|</CostExpenseID>
					<CostCategory>|schCostCategory.SelectedItems|</CostCategory>
					<CostBearerID>|schCostBearer.SelectedItems|</CostBearerID>
					<CostAtCost>|rbcCost.RadioButton1.Checked|</CostAtCost>
					<GroupBy>|schGroupBy.SelectedItems|</GroupBy>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<PeriodStart>|InitialParams.PeriodStart|</PeriodStart>
								<PeriodEnd>|InitialParams.PeriodEnd|</PeriodEnd>
								<Type>Next12Months</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<SearchCtlWinNet>
						<Group>AnalyseBy</Group>
						<ControlName>schGroupBy</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostPerUOM</DataType>
								<Caption>Group By *</Caption>
								<MaxSelectedItems>2</MaxSelectedItems>
								<MultiSelector>True</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<DropdownListControl>
						<Group>AnalyseBy</Group>
						<ControlName>dllAnalyseBy</ControlName>
						<ControlParams>
							<Items>
								<Item>MONH,Month</Item>
								<Item>QRTR,Quarter</Item>
								<Item>YEAR,Year</Item>
							</Items>
							<Properties>
								<Group.Text>Analyse By</Group.Text>
							</Properties>
						</ControlParams>
					</DropdownListControl>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schBudHeader</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetHeader</DataType>
								<Text>|InitialParams.BudgetName|</Text>
								<SelectedItems>|InitialParams.BudgetHeaderId|</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schBranch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPBranch</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schSite</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPSite</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schFleet</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPFleet</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schUOM</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPUOM</DataType>
								<MultiSelector>false</MultiSelector>
								<Caption>UOM*</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostCentre</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCostCentre</DataType>
								<Caption>Cost Centre</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCActivity</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCostActivityCC</DataType>
								<Caption>CC Activity</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCLocation</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCostLocationCC</DataType>
								<Caption>CC Location</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCResponsibility</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCostRespCC</DataType>
								<Caption>CC Responsibility</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostExpense</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCostExpense</DataType>
								<Caption>Cost Expense</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostCategory</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCategory</DataType>
								<Caption>Cost Category</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostBearer</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostBearer</DataType>
								<Caption>Cost Bearer</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<CheckBoxCollection>
						<Group>Filters</Group>
						<ControlName>cbcOHEQP</ControlName>
						<ControlParams>
							<Properties>
								<Group.Text>Include</Group.Text>
								<NumberOfCheckBoxes>2</NumberOfCheckBoxes>
								<CheckBox1.Text>OH</CheckBox1.Text>
								<CheckBox1.Width>64</CheckBox1.Width>
								<CheckBox2.Text>Eqpt</CheckBox2.Text>
							</Properties>
						</ControlParams>
					</CheckBoxCollection>
					<CheckBoxCollection>
						<Group>Filters</Group>
						<ControlName>cbcCost</ControlName>
						<ControlParams>
							<Properties>
								<Group.Text>Costs</Group.Text>
								<NumberOfCheckBoxes>2</NumberOfCheckBoxes>
								<CheckBox1.Text>To Date</CheckBox1.Text>
								<CheckBox1.Width>64</CheckBox1.Width>
								<CheckBox2.Text>Future</CheckBox2.Text>
							</Properties>
						</ControlParams>
					</CheckBoxCollection>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcCost</ControlName>
						<ControlParams>
							<Properties>
								<Group.Text>View Cost@Cost</Group.Text>
								<RadioButton1.Text>Yes</RadioButton1.Text>
								<RadioButton2.Text>No</RadioButton2.Text>
								<RadioButtonValue1>1</RadioButtonValue1>
								<RadioButtonValue2>0</RadioButtonValue2>
								<RadioButton2.Checked>true</RadioButton2.Checked>
								<RadioButton1.Checked>|InitialParams.Enable_Cost_At_Cost|</RadioButton1.Checked>
								<NumberOfRadioButtons>2</NumberOfRadioButtons>
								<Visible>|InitialParams.Enable_Cost_At_Cost|</Visible>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
				</ReportControls>
			</Text>
		</ReportTypes>
	</BUDGET_CostPerUOM_Total>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END

--Rpt_361_BUDGET_Total_Cost_Per_UOM_Report
SET @FilterConfigName = 'Rpt_361_BUDGET_Total_Cost_Per_UOM_Report'
SET @FilterConfigXML='	<Rpt_361_BUDGET_Total_Cost_Per_UOM_Report>
		<ReportName>Total Cost Per UOM</ReportName>
		<InitialParams>BudgetHeaderId,BudgetName,PeriodStart,PeriodEnd,Enable_Cost_At_Cost</InitialParams>
		<ReportTypes>
			<Text>
				<ReportFile>BudgetRptTotalCostPerUom.rpt</ReportFile>
				<ReportParams>
					<ReportHeader>Total Cost Per UOM</ReportHeader>
					<BudgetName>|InitialParams.BudgetName|</BudgetName>
					<Hierarchy>|Hierarchy.Text|</Hierarchy>
					<AddFilters>|Filters.Text|</AddFilters>
					<DateRange>|DateSelector.Text|</DateRange>
					<UOM>|schUOM.Text|</UOM>
					<txtCol1>|schAnalyseBy.Text|</txtCol1>
				</ReportParams>
				<StoredProcedure>RPT_BUDGET_TOTAL_COST_PER_UOM</StoredProcedure>
				<SpParams>
					<BudgetHeaderID>|InitialParams.BudgetHeaderId|</BudgetHeaderID>
					<UOMID>|schUOM.SelectedItems|</UOMID>
					<Next12Months>|dSelector.CheckBox.Checked|</Next12Months>
					<StartDate>|dSelector.PeriodValue1|</StartDate>
					<EndDate>|dSelector.PeriodValue2|</EndDate>
					<AnalyseBy>|schAnalyseBy.SelectedItems|</AnalyseBy>
					<IncludeOverheads>|cbcOHEQP.CheckBox1.Checked|</IncludeOverheads>
					<IncludeEquipment>|cbcOHEQP.CheckBox2.Checked|</IncludeEquipment>
					<IncludeActuals>|cbcCost.CheckBox1.Checked|</IncludeActuals>
					<IncludeProjected>|cbcCost.CheckBox2.Checked|</IncludeProjected>
					<Branch>|schBranch.SelectedItems|</Branch>
					<Site>|schSite.SelectedItems|</Site>
					<Fleet>|schFleet.SelectedItems|</Fleet>
					<CCActivity>|schCCActivity.SelectedItems|</CCActivity>
					<CCLocation>|schCCLocation.SelectedItems|</CCLocation>
					<CCResponsibility>|schCCResponsibility.SelectedItems|</CCResponsibility>
					<CostCentreID>|schCostCentre.SelectedItems|</CostCentreID>
					<CostExpenseID>|schCostExpense.SelectedItems|</CostExpenseID>
					<CostCategory>|schCostCategory.SelectedItems|</CostCategory>
					<CostBearerID>|schCostBearer.SelectedItems|</CostBearerID>
					<CostAtCost>|rbcCost.RadioButton1.Checked|</CostAtCost>
					<GroupBy>|schGroupBy.SelectedItems|</GroupBy>
				</SpParams>
				<ReportControls>
					<DateSelector>
						<Group>DateSelector</Group>
						<ControlName>dSelector</ControlName>
						<ControlParams>
							<Properties>
								<PeriodStart>|InitialParams.PeriodStart|</PeriodStart>
								<PeriodEnd>|InitialParams.PeriodEnd|</PeriodEnd>
								<Type>Next12Months</Type>
							</Properties>
						</ControlParams>
					</DateSelector>
					<SearchCtlWinNet>
						<Group>AnalyseBy</Group>
						<ControlName>schGroupBy</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostPerUOM</DataType>
								<Caption>Group By</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>AnalyseBy</Group>
						<ControlName>schAnalyseBy</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostPerUOM</DataType>
								<Caption>Analyse By*</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schBudHeader</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetHeader</DataType>
								<Text>|InitialParams.BudgetName|</Text>
								<SelectedItems>|InitialParams.BudgetHeaderId|</SelectedItems>
								<Visible>false</Visible>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schBranch</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPBranch</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schSite</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPSite</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Hierarchy</Group>
						<ControlName>schFleet</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPFleet</DataType>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schUOM</ControlName>
						<Required>true</Required>
						<ControlParams>
							<Properties>
								<DataType>BudgetUOM</DataType>
								<MultiSelector>false</MultiSelector>
								<Caption>UOM*</Caption>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostCentre</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostCentre</DataType>
								<Caption>Cost Centre</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCActivity</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostActivityCC</DataType>
								<Caption>CC Activity</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCLocation</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostLocationCC</DataType>
								<Caption>CC Location</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCCResponsibility</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostRespCC</DataType>
								<Caption>CC Responsibility</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostExpense</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetCostExpense</DataType>
								<Caption>Cost Expense</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostCategory</ControlName>
						<ControlParams>
							<Properties>
								<DataType>BudgetOHEQPCategory</DataType>
								<Caption>Cost Category</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<SearchCtlWinNet>
						<Group>Filters</Group>
						<ControlName>schCostBearer</ControlName>
						<ControlParams>
							<Properties>
								<DataType>CostBearer</DataType>
								<Caption>Cost Bearer</Caption>
								<MultiSelector>true</MultiSelector>
							</Properties>
						</ControlParams>
					</SearchCtlWinNet>
					<CheckBoxCollection>
						<Group>Filters</Group>
						<ControlName>cbcOHEQP</ControlName>
						<ControlParams>
							<Properties>
								<Group.Text>Include</Group.Text>
								<NumberOfCheckBoxes>2</NumberOfCheckBoxes>
								<CheckBox1.Text>OH</CheckBox1.Text>
								<CheckBox1.Width>64</CheckBox1.Width>
								<CheckBox2.Text>Eqpt</CheckBox2.Text>
							</Properties>
						</ControlParams>
					</CheckBoxCollection>
					<CheckBoxCollection>
						<Group>Filters</Group>
						<ControlName>cbcCost</ControlName>
						<ControlParams>
							<Properties>
								<Group.Text>Costs</Group.Text>
								<NumberOfCheckBoxes>2</NumberOfCheckBoxes>
								<CheckBox1.Text>To Date</CheckBox1.Text>
								<CheckBox1.Width>64</CheckBox1.Width>
								<CheckBox2.Text>Future</CheckBox2.Text>
							</Properties>
						</ControlParams>
					</CheckBoxCollection>
					<RadioButtonCollection>
						<Group>Filters</Group>
						<ControlName>rbcCost</ControlName>
						<ControlParams>
							<Properties>
								<Group.Text>View Cost@Cost</Group.Text>
								<RadioButton1.Text>Yes</RadioButton1.Text>
								<RadioButton2.Text>No</RadioButton2.Text>
								<RadioButtonValue1>1</RadioButtonValue1>
								<RadioButtonValue2>0</RadioButtonValue2>
								<RadioButton2.Checked>true</RadioButton2.Checked>
								<RadioButton1.Checked>|InitialParams.Enable_Cost_At_Cost|</RadioButton1.Checked>
								<NumberOfRadioButtons>2</NumberOfRadioButtons>
								<Visible>|InitialParams.Enable_Cost_At_Cost|</Visible>
							</Properties>
						</ControlParams>
					</RadioButtonCollection>
				</ReportControls>
			</Text>
		</ReportTypes>
	</Rpt_361_BUDGET_Total_Cost_Per_UOM_Report>
'

IF @FilterConfigName <> '' AND CAST(@FilterConfigXML AS VARCHAR(MAX)) <> ''
BEGIN
	IF EXISTS (SELECT * FROM AMT_FILTER_CONFIG WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID)
		BEGIN
			UPDATE AMT_FILTER_CONFIG SET FilterConfig = @FilterConfigXML,LastModDate=GetDate() WHERE FilterConfigName = @FilterConfigName AND FilterTypeID=@FilterTypeID
		END
	ELSE
		BEGIN
			INSERT INTO AMT_FILTER_CONFIG (FilterConfigName, FilterConfig,FilterTypeID) VALUES (@FilterConfigName, @FilterConfigXML,@FilterTypeID)
		END

END


