Update TASK SET Event_ID = NULL

DELETE FROM DOWN_TIME_ALLOCATION
DELETE FROM EVENT

DELETE FROM TASK_OPERATION_PART
DELETE FROM TASK_OPERATION_LABOUR
DELETE FROM TASK_OPERATION_MISC
DELETE FROM TASK_OPERATION
DELETE FROM TASK


DELETE   FROM  dbo.tblWorkOrderSettlements
DELETE   FROM  dbo.tblWorkOrderOperations
DELETE   FROM  dbo.tblWorkOrderInvoices
DELETE FROM tblWorkOrderProjs
DELETE   FROM  dbo.tblWorkOrders