DELETE  FROM KPI_TARGET WHERE Fleet_Id NOT IN (SELECT FleetId FROM tblFleets)

DELETE FROM TASK_SPECIFIC_DOWNTIME WHERE Fleet_Id NOT IN (SELECT FleetId FROM tblFleets)
GO

--ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_tblSites];
UPDATE PTA
	SET PTA.Next_Occ_Part_Location_Id = EH.SiteId
FROM tblProjTaskAmts PTA 
INNER JOIN tblProjTaskOpts PTO ON PTO.ProjTaskOptId = PTA.ProjTaskOptId
INNER JOIN tblProjTasks PT ON PT.ProjTaskId = PTO.ProjTaskId
INNER JOIN EQUIPMENT_HIERARCHY_V EH ON EH.EqpProjId = PT.EqpProjId
WHERE PTA.Next_Occ_Part_Location_Id IS NOT NULL AND PTA.Next_Occ_Part_Location_Id  NOT IN (SELECT SiteId FROM tblSites)

GO

--ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_tblSites1];
UPDATE PTA
	SET PTA.PerformedAtSiteId = EH.SiteId
FROM tblProjTaskAmts PTA 
INNER JOIN tblProjTaskOpts PTO ON PTO.ProjTaskOptId = PTA.ProjTaskOptId
INNER JOIN tblProjTasks PT ON PT.ProjTaskId = PTO.ProjTaskId
INNER JOIN EQUIPMENT_HIERARCHY_V EH ON EH.EqpProjId = PT.EqpProjId
WHERE PTA.PerformedAtSiteId IS NOT NULL AND PTA.PerformedAtSiteId  NOT IN (SELECT SiteId FROM tblSites)

GO

--FK_tblWorkOrders_tblBranches
UPDATE WO
	SET WO.BranchId = Eh.BranchId
FROM tblWorkorders WO
INNER JOIN EQUIPMENT_HIERARCHY_V EH ON EH.EqpPlanId = WO.EqpPlanId
WHERE WO.BranchId <> EH.BranchId
GO

--FK_tblWorkOrders_tblCurrencies
DECLARE @CurrencyId INT

SELECT @CurrencyId = CurrencyID FROM tblCurrencies WHERE PrimaryCurr <> 0
 
UPDATE WO
SET WO.CurrencyId = @CurrencyId
FROM tblWorkorders WO
LEFT JOIN tblCurrencies C  ON C.CurrencyID = WO.CurrencyId
WHERE C.CurrencyID IS NULL
 
 GO

--[FK_WORK_SCOPE_DOCUMENT_MODEL_FAMILY]
UPDATE  WS
SET WS.Model_Family_Id =  M.Model_Family_Id
 FROM WORK_SCOPE_DOCUMENT WS
LEFT JOIN tblModels M ON M.ModelId = WS.Model_Id
WHERE ISNULL(M.Model_Family_Id,0) <> ISNULL(WS.Model_Family_Id,0)

GO


--The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_TASK_SPECIFIC_DOWNTIME_tblTaskTypes". The conflict occurred in database "Mool_Ghana", table "dbo.tblTaskTypes", column 'TaskTypeID'.

DELETE TS
FROM 
TASK_SPECIFIC_DOWNTIME TS 
LEFT JOIN tblTaskTypes TT ON TT.TaskTypeID = TS.TaskTypeId
WHERE TT.TaskTypeID IS NULL
GO


--The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_tblWorkOrders_tblComponentCodes". The conflict occurred in database "Mool_Ghana", table "dbo.tblComponentCodes", column 'ComponentCodeID'.

DECLARE @DefaultCompCodeId INT
SELECT @DefaultCompCodeId =  ComponentCodeID FROM tblComponentCodes WHERE Default_Record <> 0
UPDATE WO
SET WO.AMTComponentCodeId = CASE WHEN T.Task_ID IS NULL THEN  @DefaultCompCodeId ELSE T.Component_Code_ID END
FROM tblWorkOrders WO 
LEFT JOIN tblComponentCodes TT ON TT.ComponentCodeID = WO.AMTComponentCodeId
LEFT JOIN TASK T ON T.Work_Order_ID = WO.WorkOrderId

WHERE TT.ComponentCodeID IS NULL


 GO
 
--The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_tblWorkOrders_tblTaskTypes". The conflict occurred in database "Mool_Ghana", table "dbo.tblTaskTypes", column 'TaskTypeID'.
DECLARE @DefaultTaskTypeId INT
SELECT @DefaultTaskTypeId =  TaskTypeId FROM tblTaskTypes WHERE Default_Record <> 0

UPDATE	WO
SET WO.AMTTaskTypeId = CASE WHEN T.Task_ID IS NULL THEN  @DefaultTaskTypeId ELSE T.Task_Type_ID END
FROM tblWorkOrders WO 
LEFT JOIN tblTaskTypes TT ON TT.TaskTypeID = WO.AmtTaskTypeId
LEFT JOIN TASK T ON T.Work_Order_ID = WO.WorkOrderId
WHERE TT.TaskTypeID IS NULL

GO

 --FK_tblWorkOrders_tblTaskTypes1
UPDATE	WO
SET WO.TaskTypeId = WO.AMTTaskTypeId
FROM tblWorkOrders WO 
LEFT JOIN tblTaskTypes TT ON TT.TaskTypeID = WO.TaskTypeId
WHERE TT.TaskTypeID IS NULL

GO


/*VV #3362 re-create constraint FK_tblSubSystems_tblComponentCodes1*/
IF EXISTS(SELECT name FROM sys.foreign_keys WHERE name = 'FK_tblSubSystems_tblComponentCodes1')
BEGIN
	ALTER TABLE dbo.tblSubSystems DROP CONSTRAINT FK_tblSubSystems_tblComponentCodes1
END

GO

ALTER TABLE dbo.tblSubSystems ADD CONSTRAINT
	FK_tblSubSystems_tblComponentCodes1 FOREIGN KEY
	(
	UnsCompCodeID
	) REFERENCES dbo.tblComponentCodes
	(
	ComponentCodeID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO


PRINT N'Checking existing data against newly created constraints';

ALTER TABLE [dbo].[tblProjTaskOpts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTasks_tblProjTaskOpts];

GO
ALTER TABLE [dbo].[COMPONENT_SERIALISED] WITH CHECK CHECK CONSTRAINT [FK_COMPONENT_SERIALISED_tblComponentCodes];

GO
ALTER TABLE [dbo].[COMPONENT_SERIALISED] WITH CHECK CHECK CONSTRAINT [FK_COMPONENT_SERIALISED_tblModels];

GO
ALTER TABLE [dbo].[COMPONENT_SERIALISED] WITH CHECK CHECK CONSTRAINT [FK_COMPONENT_SERIALISED_tblParts];

GO

ALTER TABLE [dbo].[INVENTORY_PART] WITH CHECK CHECK CONSTRAINT [FK_INVENTORY_PART_tblBranches];
GO

ALTER TABLE [dbo].[INVENTORY_PART] WITH CHECK CHECK CONSTRAINT [FK_INVENTORY_PART_tblParts];
GO

ALTER TABLE [dbo].[BUDGET_COST] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_COST_EQP_CATEGORY];
GO

ALTER TABLE [dbo].[BUDGET_EQUIPMENT] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_EQUIPMENT_AVAILABILITY_TYPE];
GO

ALTER TABLE [dbo].[BUDGET_HEADCOUNT] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_HEADCOUNT_BUDGET_HEADER1];
GO

ALTER TABLE [dbo].[BUDGET_HEADCOUNT] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_HEADCOUNT_COST_CENTRE];
GO
ALTER TABLE [dbo].[BUDGET_HEADCOUNT] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_HEADCOUNT_tblLabourActivities];
GO
ALTER TABLE [dbo].[BUDGET_OVERHEAD] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_OVERHEAD_tblFinancialPeriods];
GO
ALTER TABLE [dbo].[BUDGET_OVERHEAD] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_OVERHEAD_tblFinancialPeriods1];
GO
ALTER TABLE [dbo].[BUDGET_OVERHEAD] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_OVERHEAD_USER_ACCESS_LEVEL];
GO
ALTER TABLE [dbo].[BUDGET_PH_REVENUE] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_PH_REVENUE_COST_CENTRE];
GO
ALTER TABLE [dbo].[BUDGET_PH_REVENUE] WITH CHECK CHECK CONSTRAINT [FK_BUDGET_PH_REVENUE_COST_EXPENSE];
GO
--ALTER TABLE [dbo].[CBM_FAILURE_MODE_ASSESSMENT] WITH CHECK CHECK CONSTRAINT [FK_CBM_FAILURE_MODE_ASSESSMENT_RCM_CONDITION_MONITORING];

ALTER TABLE [dbo].[EMI_LONG_TERM_ACTION] WITH CHECK CHECK CONSTRAINT [FK_EMI_LONG_TERM_ACTION_tblJobCodes];
GO
ALTER TABLE [dbo].[EMI_SHORT_TERM_ACTION] WITH CHECK CHECK CONSTRAINT [FK_EMI_SHORT_TERM_ACTION_tblJobCodes];
GO
ALTER TABLE [dbo].[GLOBAL_COMPONENT_CODES] WITH CHECK CHECK CONSTRAINT [FK_GLOBAL_COMPONENT_CODES_tblComponentCodes];
GO
ALTER TABLE [dbo].[IMPORT_ERROR] WITH CHECK CHECK CONSTRAINT [FK_IMPORT_ERROR_IMPORT_ERROR_TYPE];
GO
ALTER TABLE [dbo].[INTERFACE_PARAMETER] WITH CHECK CHECK CONSTRAINT [FK_INTERFACE_PARAMETER_INTERFACE_TYPE];
GO
ALTER TABLE [dbo].[KPI_TARGET] WITH CHECK CHECK CONSTRAINT [FK_KPI_TARGET_tblFleets];
GO
ALTER TABLE [dbo].[MESSAGE] WITH CHECK CHECK CONSTRAINT [FK_MESSAGE_CBM_FAILURE_MODE_ASSESSMENT];
GO
ALTER TABLE [dbo].[MULTI_PROJECTION_TASK_NOTE] WITH CHECK CHECK CONSTRAINT [FK_MULTI_PROJECTION_TASK_NOTE_tblApplicationCodes];
GO
ALTER TABLE [dbo].[MULTI_PROJECTION_TASK_NOTE] WITH CHECK CHECK CONSTRAINT [FK_MULTI_PROJECTION_TASK_NOTE_tblComponentCodes];
GO
ALTER TABLE [dbo].[MULTI_PROJECTION_TASK_NOTE] WITH CHECK CHECK CONSTRAINT [FK_MULTI_PROJECTION_TASK_NOTE_tblModifierCodes];
GO
ALTER TABLE [dbo].[MULTI_PROJECTION_TASK_NOTE] WITH CHECK CHECK CONSTRAINT [FK_MULTI_PROJECTION_TASK_NOTE_tblTaskTypes];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_EMPLOYEE];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_EMPLOYEE1];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_PAY_TYPE];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_SALES_LOST_REASON];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_SALES_STATUS];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_tblParts];
GO
ALTER TABLE [dbo].[NEXT_OCC_STRATEGY] WITH CHECK CHECK CONSTRAINT [FK_NEXT_OCC_STRATEGY_tblSites];
GO

ALTER TABLE [dbo].[OVERHEAD_ACTUAL_COST] WITH CHECK CHECK CONSTRAINT [FK_OVERHEAD_ACTUAL_COST_tblEquipment];
GO

ALTER TABLE [dbo].[PH_PLANT_HIRE_RATE_DETAIL] WITH CHECK CHECK CONSTRAINT [FK_PH_PLANT_HIRE_RATE_DETAIL_PH_RATE_SOURCE];
GO
ALTER TABLE [dbo].[PH_TRANSACTION_HEADER] WITH CHECK CHECK CONSTRAINT [FK_PH_TRANSACTION_HEADER_tblQUOMs];
GO
ALTER TABLE [dbo].[RECON_GLR_DATA] WITH CHECK CHECK CONSTRAINT [FK_RECON_GLR_DATA_RECON_GLR_DATA];
GO
ALTER TABLE [dbo].[RECON_GLR_DATA] WITH CHECK CHECK CONSTRAINT [FK_RECON_GLR_DATA_SYSTEM_SOURCE];
GO
ALTER TABLE [dbo].[RECON_GLR_DATA] WITH CHECK CHECK CONSTRAINT [FK_RECON_GLR_DATA_tblCostBearers];
GO
ALTER TABLE [dbo].[SCHEDULING_TASK] WITH CHECK CHECK CONSTRAINT [FK_SCHEDULING_TASK_SYSTEM_SOURCE];
GO
--The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_SCHEDULING_TASK_tblEqpPlans".

UPDATE PT
SET PT.SchedulingTaskId = NULL
FROM tblProjTasks PT
WHERE PT.SchedulingTaskId IN 
(SELECT SchedulingTaskId FROM SCHEDULING_TASK 
WHERE  EqpPlanId NOT IN (SELECT EqpPlanId FROM tblEqpplans))

GO

UPDATE 
PT
SET PT.Scheduling_Task_Id = NULL
FROM COST_ALLOCATION PT
WHERE PT.Scheduling_Task_Id IN 
(SELECT SchedulingTaskId FROM SCHEDULING_TASK 
WHERE  EqpPlanId NOT IN (SELECT EqpPlanId FROM tblEqpplans))
GO

DELETE 
FROM SCHEDULING_TASK 
WHERE  EqpPlanId NOT IN (SELECT EqpPlanId FROM tblEqpplans)
GO

ALTER TABLE [dbo].[SCHEDULING_TASK] WITH CHECK CHECK CONSTRAINT [FK_SCHEDULING_TASK_tblEqpPlans];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_COMPONENT_SERIALISED];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_COMPONENT_SERIALISED1];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_DEF_WORK_GROUP];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_PRIORITY];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_TASK];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_tblParts];
GO
ALTER TABLE [dbo].[TASK] WITH CHECK CHECK CONSTRAINT [FK_TASK_tblPartTypes];
GO
ALTER TABLE [dbo].[TASK_OPERATION] WITH CHECK CHECK CONSTRAINT [FK_TASK_OPERATION_HEALTH_SAFETY1];
GO
ALTER TABLE [dbo].[TASK_OPERATION_LABOUR] WITH CHECK CHECK CONSTRAINT [FK_TASK_OPERATION_LABOUR_tblCurrencies];
GO
ALTER TABLE [dbo].[TASK_OPERATION_LABOUR] WITH CHECK CHECK CONSTRAINT [FK_TASK_OPERATION_LABOUR_WORK_GROUP1];
GO
ALTER TABLE [dbo].[TASK_OPERATION_MISC] WITH CHECK CHECK CONSTRAINT [FK_TASK_OPERATION_MISC_tblCurrencies];
GO
ALTER TABLE [dbo].[TASK_OPERATION_PART] WITH CHECK CHECK CONSTRAINT [FK_TASK_OPERATION_PART_tblCurrencies];
GO
ALTER TABLE [dbo].[TASK_SPECIFIC_DOWNTIME] WITH CHECK CHECK CONSTRAINT [FK_TASK_SPECIFIC_DOWNTIME_tblFleets];
GO
ALTER TABLE [dbo].[TASK_SPECIFIC_DOWNTIME] WITH CHECK CHECK CONSTRAINT [FK_TASK_SPECIFIC_DOWNTIME_tblTaskTypes];
GO
IF EXISTS(SELECT name FROM sys.foreign_keys WHERE name = 'FK_tblActualBillings_tblProjBillings')
BEGIN
	ALTER TABLE [dbo].[tblActualBillings] DROP CONSTRAINT [FK_tblActualBillings_tblProjBillings];
END
GO
IF EXISTS(SELECT name FROM sys.foreign_keys WHERE name = 'FK_tblCostPartsEscalations_tblCostEscalations')
BEGIN
	ALTER TABLE dbo.tblCostPartsEscalations DROP CONSTRAINT FK_tblCostPartsEscalations_tblCostEscalations
END

GO
--ALTER TABLE [dbo].[tblCostPartsEscalations] WITH CHECK CHECK CONSTRAINT [FK_tblCostPartsEscalations_tblCostEscalations];
GO

DELETE ST
FROM tblCostPartsEscalations ST
LEFT JOIN tblManufacturers E ON E.ManufacturerId = ST.ManufacturerId
WHERE E.ManufacturerId IS NULL
GO

ALTER TABLE [dbo].[tblCostPartsEscalations] WITH CHECK CHECK CONSTRAINT [FK_tblCostPartsEscalations_tblManufacturers];
GO
ALTER TABLE [dbo].[tblEqpPlans] WITH CHECK CHECK CONSTRAINT [FK_tblEqpPlans_EMPLOYEE];
GO
ALTER TABLE [dbo].[tblExRateCurrencies] WITH CHECK CHECK CONSTRAINT [FK_tblExRateCurrencies_tblCurrencies];
GO
ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_ENTRY_DISTRIBUTION_CODE];
GO
ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_ENTRY_DISTRIBUTION_CODE1];
GO
ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_ENTRY_DISTRIBUTION_CODE2];
GO
ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_tblPartTypes];
GO
ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_tblSites];
GO
ALTER TABLE [dbo].[tblProjTaskAmts] WITH CHECK CHECK CONSTRAINT [FK_tblProjTaskAmts_tblSites1];
GO
ALTER TABLE [dbo].[tblProjTasks] WITH CHECK CHECK CONSTRAINT [FK_tblProjTasks_COMPONENT_SERIALISED];
GO

UPDATE PT
SET PT.SchedulingTaskId = NULL
FROM tblProjTasks PT
LEFT JOIN SCHEDULING_TASK ST ON ST.SchedulingTaskId = PT.SchedulingTaskId
WHERE ST.SchedulingTaskId IS NULL
GO

ALTER TABLE [dbo].[tblProjTasks] WITH CHECK CHECK CONSTRAINT [FK_tblProjTasks_SCHEDULING_TASK];
GO
ALTER TABLE [dbo].[tblSubSystems] WITH CHECK CHECK CONSTRAINT [FK_tblSubSystems_tblComponentCodes1];
GO
ALTER TABLE [dbo].[tblUsageStepRels] WITH CHECK CHECK CONSTRAINT [FK_tblUsageStepRels_tblQUOMs];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_CAUSE];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_SYMPTOM];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_SYSTEM_SOURCE];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_TASK_HEADER];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblAMTWorkOrderStatus];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblApplicationCodes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblApplicationCodes1];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblBranches];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblComponentCodes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblComponentCodes1];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblCurrencies];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblJobCodes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblJobCodes1];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblModifierCodes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblModifierCodes1];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblOccurrenceTypes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblOccurrenceTypes1];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblQUOMs];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblTaskTypes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblTaskTypes1];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblWorkOrderStatus];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_tblWorkOrderTypes];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_WORK_ORDER_JOB_STATUS];
GO
ALTER TABLE [dbo].[tblWorkOrders] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrders_WORK_ORDER_JOB_STATUS1];
GO
ALTER TABLE [dbo].[tblWorkOrderStatus] WITH CHECK CHECK CONSTRAINT [FK_tblWorkOrderStatus_tblAMTWorkOrderStatus];
GO
ALTER TABLE [dbo].[TEST_TIME] WITH CHECK CHECK CONSTRAINT [FK_TEST_TIME_EVENT];
GO
ALTER TABLE [dbo].[TEST_TIME] WITH CHECK CHECK CONSTRAINT [FK_TEST_TIME_tblCurrencies];
GO
ALTER TABLE [dbo].[TEST_TIME] WITH CHECK CHECK CONSTRAINT [FK_TEST_TIME_tblEqpProjs];
GO
ALTER TABLE [dbo].[TEST_TIME] WITH CHECK CHECK CONSTRAINT [FK_TEST_TIME_tblExRates];
GO
ALTER TABLE [dbo].[TEST_TIME] WITH CHECK CHECK CONSTRAINT [FK_TEST_TIME_tblProjBillings];
GO
ALTER TABLE [dbo].[TEST_TIME] WITH CHECK CHECK CONSTRAINT [FK_TEST_TIME_tblQUOMs];
GO
ALTER TABLE [dbo].[WORK_SCOPE_DOCUMENT] WITH CHECK CHECK CONSTRAINT [FK_WORK_SCOPE_DOCUMENT_MODEL_FAMILY];
GO

 